Update api.md with Fast Search API Documentation
Wang-Bioinformatics-Lab/GNPS2_Documentation pull request #12
Opened 2024-01-18 15:50 UTC by Michael-C-Strobel

2024-01-18 18:59 UTC, albertogilf requested changes
Small updates.

2024-01-18 18:59 UTC, albertogilf commented on docs/api.md
> +Search by peaks:
Search by query spectrum? To be consistent with line 69

2024-01-18 18:59 UTC, albertogilf commented on docs/api.md
> +* pm_tolerance: The tolerance for precursor mass matching, defaults to 0.05
pm_tolerance (Da). I guess is Daltons because 0.05 ppm is very small, so it is good to specify the units.

2024-01-18 18:59 UTC, albertogilf commented on docs/api.md
> +* fragment_tolerance: The tolerance for matching individual peaks, defaults to 0.05
Specify units (Da)

2024-01-18 18:59 UTC, albertogilf commented on docs/api.md
> +* query_spectrum (mututally exclusive with USI): A json formatted peak list
Is there any difference with Search by Peaks?

2024-01-18 19:12 UTC, Michael-C-Strobel commented
I think all of the above should be addressed, ready for merge.

2024-01-19 12:13 UTC, albertogilf approved these changes
Cool!

2024-01-19 22:28 UTC, merged